In [16]:
import requests
import pandas as pd

In [20]:
url = 'https://archive-api.open-meteo.com/v1/archive'

params = {
    "latitude": 54.71,
    "longitude": 20.51,
    
  "start_date": "2025-01-01",
    "end_date": "2025-01-31",
    
    "hourly": "temperature_2m,precipitation,wind_speed_10m"
}

response = requests.get(url, params=params)
response.status_code

200

In [21]:
data = response.json()
data.keys()

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [22]:
df = pd.DataFrame(data["hourly"])
df.head()

               time  temperature_2m  precipitation  wind_speed_10m
0  2025-01-01T00:00             2.3            0.0            23.7
1  2025-01-01T01:00             2.4            0.1            20.6
2  2025-01-01T02:00             2.9            0.1            23.3
3  2025-01-01T03:00             3.9            0.0            26.7
4  2025-01-01T04:00             4.2            0.0            28.0

In [24]:
df["time"] = pd.to_datetime(df["time"])
df.head()

                 time  temperature_2m  precipitation  wind_speed_10m
0 2025-01-01 00:00:00             2.3            0.0            23.7
1 2025-01-01 01:00:00             2.4            0.1            20.6
2 2025-01-01 02:00:00             2.9            0.1            23.3
3 2025-01-01 03:00:00             3.9            0.0            26.7
4 2025-01-01 04:00:00             4.2            0.0            28.0